# Generated by Django 4.2.3 on 2024-10-12 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biographyauthor',
            options={'ordering': ['author_position']},
        ),
    ]
