# Generated by Django 5.2.5 on 2025-08-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_first_name_alter_author_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(),
        ),
    ]
