# Generated by Django 5.2.5 on 2025-08-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
