# Generated by Django 5.2.5 on 2026-05-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_author_biography_alter_author_first_name'),
        ('biographies', '0012_alter_biography_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biographyauthor',
            unique_together={('biography', 'author')},
        ),
    ]
