# Generated by Django 3.2.5 on 2021-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0002_auto_20210710_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
