# Generated by Django 3.2.5 on 2021-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0005_auto_20210711_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='lifespan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
