# Generated by Django 3.2.5 on 2021-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0006_alter_biography_lifespan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
