# Generated by Django 4.2.3 on 2024-09-20 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0007_alter_biography_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('biography', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='BiographyAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biographies.author')),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biographies.biography')),
            ],
            options={
                'ordering': ['biography', 'author_position'],
                'unique_together': {('biography', 'author_position'), ('biography', 'author')},
            },
        ),
        migrations.AddField(
            model_name='biography',
            name='authors_connections',
            field=models.ManyToManyField(related_name='biographies', through='biographies.BiographyAuthor', to='biographies.author'),
        ),
    ]
