# Generated by Django 4.2.3 on 2024-10-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('biographies', '0009_add_comment_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biographyauthor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='biographyauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='biographyauthor',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='biography',
        ),
        migrations.AlterField(
            model_name='biography',
            name='authors',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='authors_connections',
            field=models.ManyToManyField(related_name='biographies', through='authors.BiographyAuthor', to='authors.author'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='external_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='lifespan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='primary_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='biographies.country'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='revisions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='secondary_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='biographies.country'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BiographyAuthor',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
