# Generated by Django 5.2.5 on 2025-08-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0010_alter_biographyauthor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='authors',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='lifespan',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biography',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
