# Generated by Django 5.2.5 on 2025-08-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0011_alter_biography_authors_alter_biography_lifespan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='title',
            field=models.CharField(db_index=True),
        ),
    ]
