# Generated by Django 5.2.5 on 2026-05-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0012_alter_biography_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='authors',
            field=models.CharField(blank=True, null=True, verbose_name='Authors'),
        ),
    ]
