# Generated by Django 4.2.3 on 2024-10-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biographies', '0010_alter_biographyauthor_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('approve_key', models.CharField(blank=True, max_length=16, null=True)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biographies.biography')),
            ],
        ),
    ]
