# Generated by Django 4.2.3 on 2024-10-12 00:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0010_alter_biographyauthor_unique_together_and_more'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='biography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='biographies.biography'),
        ),
    ]
