# Generated by Django 5.1.4 on 2025-08-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_created_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(help_text='This will not be displayed publically (required).', max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(help_text='Name displayed with the comment (required).', max_length=80),
        ),
    ]
