# Generated by Django 5.2.5 on 2025-09-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approve_key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
