# Generated by Django 3.2.5 on 2021-07-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('lifespan', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('authors', models.CharField(max_length=250)),
                ('revisions', models.TextField()),
                ('external_links', models.TextField()),
                ('references', models.TextField()),
                ('south_georgia', models.BooleanField()),
                ('featured', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='biographies.country')),
                ('secondary_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='biographies.country')),
            ],
            options={
                'verbose_name_plural': 'Biographies',
                'ordering': ['title'],
            },
        ),
    ]
