# Generated by Django 3.2.5 on 2021-07-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='biography',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
