# Generated by Django 3.2.5 on 2021-07-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biographies', '0003_alter_biography_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='primary_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='biographies.country'),
        ),
    ]
