# Generated by Django 4.2.3 on 2024-09-23 05:30

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biographies', '0009_add_comment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('caption', models.TextField()),
                ('attribution', models.CharField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biographies.biography')),
            ],
        ),
    ]
