# Generated by Django 4.2.3 on 2024-09-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_add_images_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='attribution',
            field=models.CharField(null=True),
        ),
    ]
