# Generated by Django 5.1.4 on 2025-08-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_created_at_image_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['biography__title', 'id']},
        ),
    ]
