name: Build, Test and Deploy

on:
  push:
    branches:
      - development
      - main
    paths-ignore:
      - '**/README.md'
      - '.github/**'
      - '.vscode/**'
      - 'container_infra/**'
  pull_request:
    branches:
      - development
      - main

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests on the image
        run: |
          docker compose -f docker-compose-test.yml run --rm dfb-test


  build-push:
    needs: build-test
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_ENV: ${{ (github.head_ref || github.ref_name) == 'main' && 'production' || 'staging' }}
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: echo branch name
        run: |
          echo ${{ github.head_ref || github.ref_name }}
          echo ${{ github.event.repository.name }}
          echo ${{ github.repository_owner }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags:  ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.DEPLOYMENT_ENV }}


  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    environment: ${{ (github.head_ref || github.ref_name) == 'main' && 'production' || 'staging' }}
    env:
      INFRA_DIR: ${{ vars.INFRA_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/deploy.key
          chmod 0600 ~/.ssh/deploy.key
          ssh-keyscan ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Pull image for service
        run: |
          ssh -p ${{ vars.SSH_PORT }} -i ~/.ssh/deploy.key ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} <<EOF
            cd $INFRA_DIR
            docker compose pull dfb-django
          EOF

      - name: Restart service
        run: |
          ssh -p ${{ vars.SSH_PORT }} -i ~/.ssh/deploy.key ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} <<EOF
            cd $INFRA_DIR
            docker compose down --remove-orphans dfb-django
            docker compose up dfb-django -d --force-recreate
            docker compose restart nginx-staging
          EOF
