name: Deploy DFB Infrastructure
description: Deploy container infrastructure for DFB Django application to the server.

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment'
        required: true
        type: choice
        options:
          - staging
          - production


jobs:

  deploy-dfb-infra:

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
