name: Reset Featured Biographies
description: Reset featured biographies for DFB Django application.

on:
  schedule:
    - cron: "0 1 * * 0" # Runs at 01:00 UTC every Sunday
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Environment'
        required: true
        type: choice
        options:
          - staging
          - production


jobs:

  reset-biographies:

    runs-on: ubuntu-latest
    environment: ${{  github.event_name == 'schedule' && 'production' || inputs.environment_name }}
    env:
      INFRA_DIR: ${{ vars.INFRA_DIR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/deploy.key
          chmod 0600 ~/.ssh/deploy.key
          ssh-keyscan ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Reset featured biographies
        run: |
          eval $(ssh-agent -s) && ssh-add ~/.ssh/deploy.key
          ssh -p ${{ vars.SSH_PORT }} ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} <<EOF
            cd $INFRA_DIR
            docker compose run --rm dfb-django python manage.py reset_featured
          EOF
